//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobFinding_Akdeniz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company()
        {
            this.job_post = new HashSet<job_post>();
        }
    
        public int companyId { get; set; }
        public string companyName { get; set; }
        public int businessID { get; set; }
        public string foundationYear { get; set; }
        public string companyAddress { get; set; }
        public string webSiteUrl { get; set; }
        public string companyEmail { get; set; }
        public string companyPassword { get; set; }
        public string companyInfo { get; set; }
        public string companyPhone { get; set; }
        public byte[] companyLogo { get; set; }
        public System.DateTime registrationCompanyDate { get; set; }
        public string isCompanyActive { get; set; }
    
        public virtual business_stream business_stream { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_post> job_post { get; set; }
        public virtual company_log company_log { get; set; }
    }
}
