//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobFinding_Akdeniz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_experinence_detail
    {
        public int experienceId { get; set; }
        public int userAccountID { get; set; }
        public string isCurrentJob { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string jobTitle { get; set; }
        public string companyName { get; set; }
        public string description { get; set; }
    
        public virtual user_account user_account { get; set; }
    }
}
