//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobFinding_Akdeniz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_education
    {
        public int educationId { get; set; }
        public int userAccountId { get; set; }
        public string degreeName { get; set; }
        public string universityName { get; set; }
        public string startingDate { get; set; }
        public string endingDate { get; set; }
        public Nullable<double> GANO { get; set; }
        public Nullable<int> GANOINT { get; set; }
        public string department { get; set; }
    
        public virtual user_account user_account { get; set; }
    }
}
