//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobFinding_Akdeniz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_admin
    {
        public int adminAccountId { get; set; }
        public string adminEmail { get; set; }
        public string adminName { get; set; }
        public string adminSurname { get; set; }
        public string adminPassword { get; set; }
        public string adminIsActive { get; set; }
        public System.DateTime adminRegisterDate { get; set; }
        public string adminResetCode { get; set; }
    
        public virtual admin_log admin_log { get; set; }
    }
}
